<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt_BR" lang="pt_BR">
    <head>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->jQuery() ?>
        <?php echo $this->headScript() ?>        
    </head>
    <body <?php echo $this->body_params; ?>>
        <div id="container">
            <div id="header">
                <?php echo $this->render( 'header.phtml' ); ?>
            </div>

            <div id="content">
                <?php
                echo ( $this->title ) ? ('<h1>' . $this->escape( $this->title ) . '</h1>') : '';
                echo $this->flashMessages();
                echo $this->layout()->content;
                ?>
            </div>

            <div id = "footer">
                <?php echo $this->render( 'footer.phtml' ); ?>
            </div>         
        </div>
    </body>
</html>