<a href="<?php echo $this->url( array( 'controller' => 'index', 'action' => 'index' ) ) ?>">home</a>

<?php if ( Zend_Auth::getInstance()->hasIdentity() ): ?>
    <?php echo Zend_Auth::getInstance()->getIdentity()->getInstrument() ?>
    <?php echo $this->translate( "bem-vindo" ) . ', ' . Zend_Auth::getInstance()->getIdentity()->getName() . ' - '; ?>
    <a href="<?php echo $this->url( array( 'controller' => 'user', 'action' => 'logout' ) ) ?>"><?php echo $this->translate( "sair" ) ?></a>
<?php else: ?>
    <a href="<?php echo $this->url( array( 'controller' => 'user', 'action' => 'login' ) ) ?>">login</a>,
    <a href="<?php echo $this->url( array( 'controller' => 'user', 'action' => 'sign-up' ) ) ?>"><?php echo $this->translate( "cadastre-se" ) ?></a>
<?php endif; ?>